### ISSUE TITLE
Add the ability to change the number of districts when redistricting.

### ISSUE THREAD

**Issue by Devetec** [districtr/districtr#234]
I wanted to see how would districts look with more or less in each state, as I'm working on a project where the states have an alternate amount of districts. I love this tool, but if this was added it would be even better. Thanks!

**Comment by mapmeld** [comment]
Is it a state which is expected to change number of districts after the 2020 Census results come in? We could add an option in this case

Otherwise, you can export your existing districts as CSV, create a new Communities of Interest map, and drag-and-drop the CSV onto the map. There can be over 200 communities on a map... only downside is you will not have election results

**Comment by Devetec** [comment]
Yes, it is a state where the expected number of districts would change. And also, I know that Communities exist, but they don't have election results.

**Comment by mapmeld** [comment]
I'd be interested in adding this option; let me know more info about the state, or if you want to write it yourself, we have districting options for each state in ```assets/data/response.json``` of this GitHub project

**Comment by mapmeld** [comment]
Now active on Minnesota; we can deploy it to your state on request
